#include <iostream>
#include <string>
#include "Enigma.h"

using namespace std;

int main(void)
{
	Enigma enigma1;
	// 215 AAA FRA "ABIRUXKP" PCDAONONEBCJBOGLYMEEYGSHRYUBUJHMJOQZLEX
	// Should encrypt to      ANBULMEGRAZGOESTINGSTRENGGEHEIMEMELDUNG
	enigma1.SetConfig("215 AAA FRA ABIRUXKP");
	cout << enigma1.Encrypt("PCDAONONEBCJBOGLYMEEYGSHRYUBUJHMJOQZLEX");
	/*enigma1.SetConfig("245 BUL BLA AVBSCGDLFUHZINKMOWRX");
	cout << enigma1.Encrypt("EDPUDNRGYSZRCXNUYTPOMRMBOFKTBZREZKMLXLVEFGUEYSIOZVEQMIKUBPMMYLKLTTDEISMDICAGYKUACTCDOMOHWXMUUIAUBSTSLRNBZSZWNRFXWFYSSXJZVIJHIDISHPRKLKAYUPADTXQSPINQMATLPIFSVKDASCTACDPBOPVHJK");*/
	

	cin.get();
	return 0;
}